server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.57.131
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.57.131
#自定义配置
ly:
  sms:
    accessKeyId:   # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_172741809 # 模板名称
